- name: Build image
  command: docker build -t {{ image_name }} {{ build_path }}
  notify: Create nginx container

- name: Create nginx container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: started
    recreate: yes
    published_ports:
      - "80:80"