name: Ansible Lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: ansible/playbook.yml
          override-deps: |
            ansible==2.10.2
            ansible-lint==5.0.12
          args: ""