name: Terraform Validate
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Terraform Validate
        run: terraform validate
